apiVersion: v1 
kind: Pod 
metadata: 
  name: lb-pod 
  labels: 
    app: lbpod
  namespace: dev
spec: 
  containers: 
  - name: nginx-container
    image: nginx:latest
    ports:
      - name: nginxport
        containerPort: 80