apiVersion: v1 
kind: Service 
metadata: 
  name: my-np-svc
  labels: 
    app: nppod 
spec: 
  type: NodePort 
  selector:
    app: nppod
  ports:
  - name: nginx-port 
    protocol: TCP
    port: 80
    targetPort: 80