apiVersion: apps/v1 
kind: ReplicaSet 
metadata: 
  name: my-rs
  labels: 
    app: rs 
spec: 
  replicas: 3 
  selector:
    matchLabels: 
      app: rs 
  template: 
    metadata: 
      name: rs-template 
      labels: 
        app: rs 
    spec: 
      containers:
        - name: rs-container
          image: nginx:latest 
          ports:
            - containerPort: 80